In [1]:
# UT-TOR-DATA-PT-01-2020-U-C Group Project 3
# Final project
# Scrape poll based predictions
# (c) Boris Smirnov

In [2]:
import pandas as pd

In [3]:
url = 'https://338canada.com/districts.htm'

In [4]:
tables = pd.read_html(url)
feds_s = tables[0]['Electoral district'].map(lambda s: s.split(' ')[0])
proj_s = tables[0]['Latest projection'].map(lambda s: s.split(' ')[0])
proj_df = pd.DataFrame([feds_s, proj_s]).transpose()

In [10]:
toss_df = proj_df.loc[proj_df['Latest projection'] == 'Toss']

In [13]:
toss_df

    Electoral district Latest projection
24               13003              Test
32               24001              Test
39               24008              Test
44               24013              Test
49               24018              Test
65               24034              Test
74               24043              Test
80               24049              Test
82               24051              Test
93               24062              Test
107              24076              Test
114              35005              Test
127              35018              Test
131              35022              Test
135              35026              Test
148              35039              Test
151              35042              Test
165              35056              Test
176              35067              Test
180              35071              Test
225              35116              Test
226              35117              Test
236              46006              Test
241              46011              Test
247              47003              Test
253              47009              Test
275              48017              Test
306              59014              Test
307              59015              Test
309              59017              Test
328              59036              Test

In [14]:
results_lst = ['LPC', 'BQ',  'LPC', 'LPC', 'BQ',  'LPC', 'LPC', 'BQ',  'CPC', 'LPC', 'LPC', 'CPC', 'LPC', 'CPC', 'CPC',
               'LPC', 'LPC', 'CPC', 'LPC', 'LPC', 'LPC', 'NDP', 'CPC', 'LPC', 'CPC', 'CPC', 'CPC', 'LPC', 'NDP', 'CPC',
               'LPC']

In [15]:
proj_df.loc[proj_df['Latest projection'] == 'Toss', 'Latest projection'] = results_lst

In [ ]:
proj_df.rename(columns={'Electoral district': 'FED Id', 'Latest projection': 'Winning Pid'}, inplace=True)

rename_dct = {
    'LPC': 'LIB',
    'CPC': 'CPC',
    'NDP': 'NDP',
    'BQ': 'BQ',
    'GPC': 'GRN',
    'PPC': 'OTH',
    'IND': 'OTH'
}

proj_df['Winning Pid'] = proj_df['Winning Pid'].map(lambda x: rename_dct[x])

In [26]:
proj_df.to_csv('projection.csv', index=False)